# This Docker Compose file defines the deployment of a FHIR appliance and Portainer.

version: "3.2"

services:
  # FHIR Appliance Service
  fhir-appliance:
    image: synaneticsltd/synfhir-store:1.0.0 # Docker image for the FHIR appliance
    restart: always # Always restart the container if it stops
    container_name: fhir-appliance # Name of the container
    environment:
      # Environment variables required by moleculer
      - METRICSENABLE=false
      - NAMESPACE=fhir-appliance
      - NODE_ENV=production
      - SERVICEDIR=services
      - SERVICES=**/*.service.js
    env_file:
      - .env # External environment file
    ports:
      # Port mappings
      - 443:443 # Public endpoint (https)
      - 8300:8300 # Integration endpoint (http)
    volumes:
      # Volume mappings
      - ./ssl:/app/ssl # SSL certificates
      - ./jwt:/app/jwt # JSON web token verification keys
      - ./pix:/app/pix # Client certificates and keys for PIX service
    networks:
      - default # Default network

  # Portainer Service
  portainer:
    image: portainer/portainer.ce # Docker image for Portainer
    ports:
      - "9000:9000" # Portainer web interface
      - "8000:8000" # Portainer agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker socket for managing Docker
      - portainer_data:/data # Data volume for Portainer
    restart: always # Always restart the container if it stops

volumes:
  data: # Named volume for storing data
  portainer_data: # Named volume for Portainer