version: "3.2"

# Deployment of a FHIR appliance

services:
  fhir-appliance:
    image: synaneticsltd/synfhir-store:linux-latest #Old Image for Testing
    restart: always
    container_name: fhir-appliance
    environment:
      # Settings required by moleculer (not configurable)
      - METRICSENABLE=false
      - NAMESPACE=fhir-appliance
      - NODE_ENV=production
      - SERVICEDIR=services
      - SERVICES=**/*.service.js
    env_file:
      - .env
    ports:
      # Public endpoint (https)
      # Map 443 of the host to 443 in the container if using SSL
      - 443:443
      # Integration endpoint (https)
      #- 8443:8443
      # Public endpoint (http - not recommended for production - UNLESS this is an internal link and fronted by a 3rd party web proxy which provides SSL termination)
      #- 3000:3000
      # Integration endpoint (http)
      - 8300:8300
    volumes:
      # Copy .pem formatted SSL certificates: certificate, private key, passphrase (optional) and, if using mutal tls, root CA certificate to ./ssl if securing the endpoint
      # For windows server/windows containers use
      # - ./ssl:C:/app/ssl
      - ./ssl:/app/ssl
      # If using public key based JSON web token verification then copy public key of CA to ./jwt folder (see environment file for information)
      - ./jwt:/app/jwt
      # For windows server/windows containers use
      # - ./jwt:C:/app/jwt
      # If publishing patient registrations to regional PIX service then copy your client certificates and keys to this folder
      - ./pix:/app/pix
      # For windows server/windows containers use
      # - ./pix:C:/app/pi

    networks:
      - default
portainer:
    image: portainer/portainer.ce
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
volumes:
  data: